# Generated by Django 3.2 on 2021-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='drink',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Juice', 'Juice'), ('Hot Water', 'Hot Water'), ('Cold Water', 'Cold Water'), ('Soda', 'Soda'), ('Cappuccino', 'Cappuccino')], default='Tea', max_length=200),
        ),
    ]
